import Head from "next/head";
import Link from "next/link";

export default function Layout({ loggedIn, children }) {
  const logout = () =>
    fetch("/api/logout").then(() => {
      window.location.reload();
    });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "0.5rem 2rem",
        }}
      >
        <Link href="/">
          <a>
            <h1>Dating App</h1>
          </a>
        </Link>
        {loggedIn ? (
          <button onClick={logout}>Logout</button>
        ) : (
          <Link href="/app">
            <a>App</a>
          </Link>
        )}
      </header>
      <main>{children}</main>
    </>
  );
}
